---
apiVersion: v1
kind: Service
metadata:
  name: postgres-test
  labels:
    app: postgres-test
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-test
  labels:
    app: postgres-test
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-test
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: POSTGRES_USER
# Note:
# For testing, this Postgres instance will not
# persist the data and will be in the container.
# When the container is deleted or restarted, data will be lost.
# If you want a persistent Postgres instance,
# mount a volume in /var/lib/postgresql/data.
