---
apiVersion: v1
kind: Service
metadata:
  name: shop
  labels:
    app: shop
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: shop
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shop
  labels:
    app: shop
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - name: shop
          image: <ur-dockerregistry-image>
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: POSTGRES_USER
      # imagePullSecrets:
      #   - name: <pull-secret>